name: release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.18 ]
    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/get-version
      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go build -v && go test ./...
      - name: Build for linux/amd64
        run: go build -o terraformer-all-linux-amd64
      - name: Build for linux/arm64
        run: GOOS=linux GOARCH=arm64 go build -o terraformer-all-linux-arm64
      - name: Build for mac
        run: GOOS=darwin go build -o terraformer-all-darwin-amd64
      - name: Build for mac Apple Silicon
        run: GOOS=darwin GOARCH=arm64 go build -o terraformer-all-darwin-arm64
      - name: Build for all providers
        run: go run build/multi-build/main.go

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
          files: |
            hey-*